#!/usr/bin/env bash

package_name=$1
package_dir=node_modules/$package_name
main=node -e "console.log(require('$package_dir/package.json').main)"
yarn esbuild --bundle --minify --format=esm --outfile=$package_name.bundle.js ./$package_dir/$main